// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARlherAkT4XtAYmQnnwHEOzsOKM_CWhFE',
    appId: '1:29853783417:web:54db904271289230150ba8',
    messagingSenderId: '29853783417',
    projectId: 'veggiemart-7271f',
    authDomain: 'veggiemart-7271f.firebaseapp.com',
    storageBucket: 'veggiemart-7271f.firebasestorage.app',
    measurementId: 'G-GG8MRLBFT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsnuxqLhM776YoGIPLqtloNsN8urjtlCI',
    appId: '1:29853783417:android:e51000d2590396eb150ba8',
    messagingSenderId: '29853783417',
    projectId: 'veggiemart-7271f',
    storageBucket: 'veggiemart-7271f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuj69D8YCpsmxeYfOPhdFI6wuU2ODsutY',
    appId: '1:29853783417:ios:bb403c583719b437150ba8',
    messagingSenderId: '29853783417',
    projectId: 'veggiemart-7271f',
    storageBucket: 'veggiemart-7271f.firebasestorage.app',
    iosBundleId: 'com.example.week5Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuj69D8YCpsmxeYfOPhdFI6wuU2ODsutY',
    appId: '1:29853783417:ios:bb403c583719b437150ba8',
    messagingSenderId: '29853783417',
    projectId: 'veggiemart-7271f',
    storageBucket: 'veggiemart-7271f.firebasestorage.app',
    iosBundleId: 'com.example.week5Project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARlherAkT4XtAYmQnnwHEOzsOKM_CWhFE',
    appId: '1:29853783417:web:9959d9412606fba8150ba8',
    messagingSenderId: '29853783417',
    projectId: 'veggiemart-7271f',
    authDomain: 'veggiemart-7271f.firebaseapp.com',
    storageBucket: 'veggiemart-7271f.firebasestorage.app',
    measurementId: 'G-KQQF68SYHF',
  );
}
